### ISSUE TITLE
获取插件 nonebot_plugin_hikarisearch __zx_plugin_name__ 失败...，插件控制未加载

### ISSUE THREAD

**Issue by TDuckQWQ** [MeetWq/nonebot-plugin-hikarisearch#3]
![image](https://user-images.githubusercontent.com/62102282/184500137-9635494a-c457-4c51-8809-a95c9eba6791.png)
这个是什么意思（

**Comment by MeetWq** [comment]
这是真寻插件的一些字段，本插件并未定义这些字段，不影响使用，但无法使用真寻的插件开关之类的控制功能
可以自己去看真寻的文档
