### ISSUE TITLE
能改它的触发关键词吗

### ISSUE THREAD

**Issue by DragonSauce** [MeetWq/nonebot-plugin-hikarisearch#9]
能改它的触发关键词吗，如题，总是与其他的识图冲突

**Comment by eigeen** [comment]
可以修改源码

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-hikarisearch/blob/11b34d5800e3962b0981e5a89e5d7a0179c36092/nonebot_plugin_hikarisearch/__init__.py#L127
可以自行修改源码
